[multiheat]
version = "0.0.1"
temp-unit = "K"

[[hot]]
in = 340
load = 1.9

[[hot]]
in = 390
load = 1.4311

[[hot]]
in = 420
load = 2.5944

[[hot]]
in = 475
load = 1.9991

[[cold]]
in = 350
load = 0.9925

[[cold]]
in = 375
load = 1.8012

[[cold]]
in = 400
load = 4.3616
